#!/usr/bin/env node
/* Builds agreement-page-embed.html: one HTML block that loads the agreement
   page's candidate CSS and JS on the live iMIS page, for testing before the
   candidates are promoted into the theme. Paste the output into a Content
   HTML iPart at the top of the page.

     node prototypes/wip/agreement-page/build-embed.cjs          write it
     node prototypes/wip/agreement-page/build-embed.cjs --check  exit 1 if stale

   Order matters, as on index.html:
   - Before the theme (zUnionSuite.js): the task-rows candidate, which only
     takes over if it registers first, and the contacts preset, which must
     expand its classes before the theme sets up search and actions.
   - After the theme and ActionDefinitions.js: the agreement actions, which
     need UnionSuiteActions, then the remaining candidates. The theme loads
     asynchronously (UnionSuite-Core/index.js), so this half waits for it.
   Not included: notes-reading.candidate.* (Notes use the ledger, option 4)
   and the prototype-only agreement-page.*. */
'use strict';

const fs = require('fs');
const path = require('path');

const dir = __dirname;
const output = path.join(dir, 'agreement-page-embed.html');
const styles = ['theme-candidate.css', 'contacts-options.candidate.css', 'contacts-directory.candidate.css'];
const beforeTheme = ['theme-candidate-task-rows.js', 'contacts-preset.candidate.js'];
const afterTheme = ['agreement-actions.candidate.js', 'theme-candidate.js', 'contacts-options.candidate.js', 'contacts-directory.candidate.js'];

function read(name) {
  const text = fs.readFileSync(path.join(dir, name), 'utf8').replace(/\r\n/g, '\n').trimEnd();
  // A closing tag inside the content would end the inline element early.
  if (/<\/(script|style)/i.test(text)) throw new Error(name + ' contains a closing script or style tag.');
  return text;
}

const indent = (text, spaces) => text.split('\n').map(line => line ? ' '.repeat(spaces) + line : line).join('\n');
const section = (name, spaces) => indent('/* ── ' + name + ' ── */\n' + read(name), spaces);

const html = `<!-- Agreement page · candidate theme additions for testing on the live page.
     GENERATED by prototypes/wip/agreement-page/build-embed.cjs; do not edit.
     Rebuild after changing any candidate file.

     Content HTML iPart: no title, border off. Put it FIRST on the page, above
     the banner, so its first script runs before the theme's task code.
     Sources: ${styles.concat(beforeTheme, afterTheme).join(', ')}.

     Check in the browser console: UnionSuiteAgreementEmbed.status().
     taskRows false means the theme loaded first; ticks then stay on screen
     only and are not saved. Remove this iPart once the candidates are
     promoted into the theme. -->
<style>
${styles.map(name => section(name, 2)).join('\n\n')}
</style>
<script>
(function () {
  'use strict';
  if (window.UnionSuiteAgreementEmbed) return;
  const state = {themeLoadedFirst: !!window.UnionSuiteTaskRows, taskRows: false, afterTheme: 'waiting'};
  window.UnionSuiteAgreementEmbed = Object.freeze({status: () => ({...state})});

  // ── Before the theme ──────────────────────────────────────────
${beforeTheme.map(name => section(name, 2)).join('\n\n')}

  state.taskRows = typeof window.UnionSuiteTaskRows?.defineSaver === 'function';
  if (!state.taskRows) console.warn('[Agreement embed] The theme loaded first, so agreement task ticks will not be saved. Move this iPart to the top of the page.');

  // ── After the theme and ActionDefinitions.js ──────────────────
  function afterTheme() {
${afterTheme.map(name => section(name, 4)).join('\n\n')}
  }

  const themeReady = () => typeof window.UnionSuiteActions?.define === 'function' && window.UnionSuiteActions.has?.('home.manage-bulletin') === true;
  const started = Date.now();
  (function wait() {
    if (themeReady()) {
      try {
        afterTheme();
        state.afterTheme = 'ready';
      } catch (error) {
        state.afterTheme = 'failed: ' + error.message;
        console.error('[Agreement embed]', error);
      }
    } else if (Date.now() - started > 20000) {
      state.afterTheme = 'timed out: the theme did not load';
      console.error('[Agreement embed] The theme (zUnionSuite.js, ActionDefinitions.js) did not load within 20 seconds.');
    } else {
      setTimeout(wait, 50);
    }
  })();
})();
</script>
`;

if (process.argv.includes('--check')) {
  const current = fs.existsSync(output) ? fs.readFileSync(output, 'utf8') : '';
  if (current !== html) {
    console.error('agreement-page-embed.html is stale. Run: node prototypes/wip/agreement-page/build-embed.cjs');
    process.exit(1);
  }
  console.log('agreement-page-embed.html is current.');
} else {
  fs.writeFileSync(output, html);
  console.log('Wrote ' + path.relative(process.cwd(), output) + ' (' + Math.round(html.length / 1024) + ' KB).');
}
