const assert=require('node:assert/strict');const path=require('node:path');
const {chromium}=require(path.resolve(__dirname,'../../.tmp-iqa-integration/node_modules/playwright'));const {startServer}=require('../tools/preview.cjs');const {ids,pages}=require('./fixtures.cjs');
(async()=>{const service=await startServer({config:{urlParameter:'Directory',urlValue:'name'}});const browser=await chromium.launch({channel:'msedge',headless:true});try{
const p=await browser.newPage();const ready=()=>p.waitForFunction(()=>window.UnionSuiteCCO?.diagnostics()[0]?.frames.some(f=>f.state==='ready'));
await p.goto(service.url+'/?ID=1001&Directory=Overview');await ready();assert.equal(await p.getByRole('tab',{name:'Overview',exact:true}).getAttribute('aria-selected'),'true');
await p.getByRole('tab',{name:'People search',exact:true}).click();await p.waitForFunction(()=>window.UnionSuiteCCO.diagnostics()[0].frames.length===2&&window.UnionSuiteCCO.diagnostics()[0].frames.every(f=>f.state==='ready'));
assert.equal(new URL(p.url()).searchParams.get('Directory'),'People-search');assert.equal(service.requests.filter(r=>r.pathname==='/api/ContentItem').length,1);
const frame=p.frameLocator('.us-cco__panel:not([hidden]) iframe');await frame.locator('#search').evaluate(n=>{n.setAttribute('type','search')});await frame.locator('#search').fill('retain');assert.equal(await p.evaluate(()=>window.UnionSuiteCCO.diagnostics()[0].frames.some(f=>f.dirty)),false);
await frame.locator('#search').evaluate(n=>{n.type='text';const wrapper=document.createElement('div');wrapper.className='FilterPanel';n.before(wrapper);wrapper.append(n)});await frame.locator('#search').fill('filter');assert.equal(await p.evaluate(()=>window.UnionSuiteCCO.diagnostics()[0].frames.some(f=>f.dirty)),false);
await p.getByRole('tab',{name:'Overview',exact:true}).click();await p.goBack();assert.equal(await frame.locator('#search').inputValue(),'filter');
const req=service.requests.filter(r=>r.pathname.includes('ContentPreview')).map(r=>new URL(r.search,service.url));assert(req.every(u=>!u.searchParams.has('Directory')&&u.searchParams.get('ID')==='1001'));
await frame.locator('#search').evaluate(n=>{n.parentElement.className=''});await frame.locator('#search').fill('edit');assert.equal(await p.evaluate(()=>window.UnionSuiteCCO.diagnostics()[0].frames.some(f=>f.dirty)),true);
await p.evaluate(()=>window.UnionSuiteCCO.dispose());service.options.config.urlValue='number';await p.goto(service.url+'/?Directory=2');await ready();assert.equal(await p.getByRole('tab',{name:'Overview',exact:true}).getAttribute('aria-selected'),'true');await p.getByRole('tab',{name:'Finance',exact:true}).click();assert.equal(new URL(p.url()).searchParams.get('Directory'),'3');
await p.goto(service.url+'/?two&Directory=1');await p.getByText(/Another CCO uses this URL parameter/).waitFor();
service.options.config.urlParameter='ID';await p.goto(service.url);await p.getByText(/identity and renderer parameters are reserved/).waitFor();
service.options.config={urlParameter:'Directory',urlValue:'name'};service.options.folderResponse={IsSuccessStatusCode:true,Result:{$values:pages.map(x=>({...x,AlternateName:'Same'}))}};await p.goto(service.url+'/?Directory=2');await ready();assert.equal(await p.getByRole('tab').nth(1).getAttribute('aria-selected'),'true');await p.getByRole('tab').nth(2).click();assert.equal(new URL(p.url()).searchParams.get('Directory'),ids.pages[2]);
await p.goto(service.url+'/config-demo');await p.locator('[data-setting=urlParameter]').fill('Directory');await p.locator('[data-setting=urlValue]').selectOption('name');await p.getByRole('button',{name:'Save',exact:true}).click();const saved=JSON.parse(await p.locator('#JsonSettings').inputValue());assert.equal(saved.urlParameter,'Directory');assert.equal(saved.urlValue,'name');
console.log('PASS named/numbered deep links, retained Back/Forward, context isolation, duplicate/reserved-name protection, duplicate labels, search filters stay clean, real edits stay protected and editor save.');
}finally{await browser.close();await new Promise(r=>service.server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
