const key = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const ids = { content: key(1), copy: key(4), placement: key(2), second: key(9), folder: key(3), pages: [key(10), key(11), key(12)] };
const pages = ['People search', 'Overview', 'Finance'].map((caption, index) => ({ DocumentTypeId: 'CON', DocumentVersionId: ids.pages[index], Name: `${index + 1}-${caption}`, AlternateName: caption, Status: 'Published' }));
function mount(parent = ids.content, placement = ids.placement) { return `<div class="us-cco" data-us-cco data-content-key="${parent}" data-content-item-key="${placement}">Loading content pages…</div>`; }
function wrap(html, type = 'direct') {
  const body = type === 'none' ? html : `<div class="panel">${html}</div>`;
  return `<div class="ContentItemContainer">${type === 'wrapped' ? `<div class="author-class">${body}</div>` : type === 'empty' ? `<div class="">${body}</div>` : body}</div>`;
}
function parentHtml({ wrapper = 'direct', two = false, copy = false } = {}) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UnionSuite CCO local trial</title><link rel="stylesheet" href="/theme.css"><link rel="stylesheet" href="/cco.css"><style>body{margin:0;background:#eeeeef;font:14px/1.5 system-ui;color:#545962}main{max-width:1180px;margin:32px auto;padding:0 20px}header{margin-bottom:24px}h1{color:#003a4c;margin:6px 0}.eyebrow{font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:#00506a}.ContentItemContainer{margin-bottom:24px;border:1px solid #e2e5e9;border-radius:8px;overflow:hidden}.demo-note{max-width:800px}.us-cco{--us-cco-frame-height:480px}</style></head><body><main><header><span class="eyebrow">UnionSuite · component development</span><h1>Content collection</h1><p class="demo-note">Local fixture with synthetic content. Select a tab, type in its search field, switch away and return. No iMIS connection or production deployment.</p><a href="/config-demo">Open configuration editor fixture</a></header><form id="host-form"><input id="__RequestVerificationToken" name="__RequestVerificationToken" type="hidden" value="fixture-token">${wrap(mount(copy ? ids.copy : ids.content), wrapper)}${two ? wrap(mount(ids.content, ids.second), 'wrapped') : ''}</form></main><script>window.parentSubmits=0;document.getElementById('host-form').addEventListener('submit',e=>{e.preventDefault();window.parentSubmits++});window.popupCalls=[];window.ShowDialog_NoReturnValue=function(...args){window.popupCalls.push({parentThis:this===window,callback:args[11]});args[11]?.();return 'parent-popup'};window.timing=[];document.addEventListener('us-cco:timing',e=>window.timing.push(e.detail),true);</script><script src="/runtime.js"></script></body></html>`;
}
function childHtml(id, query) {
  const index = ids.pages.indexOf(id), caption = pages[index]?.AlternateName || 'Content page';
  const context = JSON.stringify(query.get('ID') || '1001').replaceAll('<', '\\u003c');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${caption}</title><style>body{font:14px/1.5 system-ui;margin:0;padding:24px;color:#545962}h2{color:#003a4c;margin-top:0}input,button{font:inherit;padding:9px 12px;border:1px solid #9aa1aa;border-radius:4px}input{margin:6px 12px 16px 0;max-width:75%}button{background:#eef6f9;color:#00506a;cursor:pointer}table{border-collapse:collapse;width:100%;margin-top:20px}th,td{text-align:left;padding:12px;border-bottom:1px solid #e2e5e9}th{background:#f8f9fa}.caption{font-size:12px;color:#545962}</style></head><body><h2>${caption}</h2><p class="caption">Synthetic child content · Member context <span id="context"></span></p><label>Search this page<br><input id="search" placeholder="Name or keyword"></label><button id="dialog" type="button">Edit example</button><p id="result" role="status">No changes saved</p><table><thead><tr><th>Name</th><th>Membership</th><th>Status</th></tr></thead><tbody><tr><td>Alex Example</td><td>Community</td><td>Active</td></tr><tr><td>Sam Sample</td><td>Workplace</td><td>Active</td></tr></tbody></table><script>document.getElementById('context').textContent=${context};window.nativeDialogs=0;window.ShowDialog_NoReturnValue=function(){window.nativeDialogs++};window.saved=0;window.callback=function(){window.saved++;document.getElementById('result').textContent='Saved in originating child '+window.saved;document.dispatchEvent(new CustomEvent('us-cco:clean'))};document.getElementById('dialog').onclick=function(){ShowDialog_NoReturnValue('/example',null,'90%','90%','Example',null,null,null,null,false,false,window.callback,null)};</script></body></html>`;
}
module.exports = { key, ids, pages, mount, wrap, parentHtml, childHtml };
