const assert=require('node:assert/strict');const path=require('node:path');
const {chromium}=require(path.resolve(__dirname,'../../.tmp-iqa-integration/node_modules/playwright'));
const {startServer}=require('../tools/preview.cjs');const {ids}=require('./fixtures.cjs');
(async()=>{const service=await startServer();const browser=await chromium.launch({channel:'msedge',headless:true});
try{const page=await browser.newPage();let queries=[];let fail=false;
await page.route('**/api/query?**',async route=>{const url=new URL(route.request().url());queries.push(url);if(fail)return route.fulfill({status:403,body:'{}'});
const row={Name:'Example folder',DocumentPath:'@/Folder & <example>',DocumentVersionKey:ids.folder};
await route.fulfill({contentType:'application/json',body:JSON.stringify({Items:{$values:[row,{DocumentVersionKey:'bad',DocumentPath:'bad',Name:'bad'}]}})});});
await page.goto(service.url+'/config-demo');await page.locator('[data-folder-search]').fill('Member & Staff');
await page.locator('[data-folder-search-results] button').waitFor();assert.equal(queries[0].searchParams.get('queryname'),'$/_i4u_/Core/Admin/CFL Search');assert.equal(queries[0].searchParams.get('Path'),'Member & Staff');assert.equal(queries[0].searchParams.get('limit'),'20');
assert.equal(queries[0].searchParams.has('parameter'),false);
await page.locator('[data-folder-search]').fill('CFL');await page.locator('[data-folder-search-results] button').waitFor();assert.equal(queries.at(-1).searchParams.get('Path'),'CFL');
assert.match(await page.locator('[data-folder-search-status]').textContent(),/1 invalid/);
await page.locator('[data-folder-search-results] button').focus();await page.keyboard.press('Enter');
assert.equal(await page.locator('[data-setting=folderDocumentVersionId]').inputValue(),ids.folder);assert.equal(await page.locator('[data-setting=folderPathLabel]').inputValue(),'@/Folder & <example>');
const saved=await page.locator('#JsonSettings').inputValue();assert.equal(JSON.parse(saved).folderPathLabel,'@/Folder & <example>');assert.deepEqual(JSON.parse(saved).foreignProperty,{retained:true});
await page.locator('[data-folder-search]').fill('');await page.getByRole('button',{name:'Find folders',exact:true}).click();await page.locator('[data-folder-search-results] button').waitFor();assert.equal(queries.at(-1).searchParams.has('Path'),false);
fail=true;await page.getByRole('button',{name:'Find folders',exact:true}).click();await page.getByText(/HTTP 403/).waitFor();assert.equal(await page.locator('#JsonSettings').inputValue(),saved);
await page.locator('[data-folder-search]').fill('cancel on dispose');const count=queries.length;await page.evaluate(()=>window.UnionSuiteCCOEditor.dispose());await page.waitForTimeout(400);assert.equal(queries.length,count);
await page.reload();await page.screenshot({path:'references/test-output/config-desktop.png',fullPage:true});
console.log('PASS IQA query and encoded named Path filter, blank browse, direct result field selection, invalid row rejection, keyboard selection, JSON auto-sync, denied search preserves settings and pending search disposal.');
}finally{await browser.close();await new Promise(r=>service.server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
