const assert=require('node:assert/strict');const path=require('node:path');
const {chromium}=require(path.resolve(__dirname,'../../.tmp-iqa-integration/node_modules/playwright'));const {startServer}=require('../tools/preview.cjs');const {ids}=require('./fixtures.cjs');
(async()=>{const service=await startServer({frameDelay:{[ids.pages[0]]:900,[ids.pages[1]]:900}});const browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage();await page.goto(service.url);const tabs=page.getByRole('tab');await tabs.first().locator('[data-us-cco-spinner]').waitFor();
assert.equal(await tabs.first().getAttribute('aria-busy'),'true');assert.equal(await page.locator('.us-cco__status').evaluate(n=>n.classList.contains('us-cco__sr-only')),true);
assert.equal(await page.locator('.us-cco__frame').first().evaluate(n=>getComputedStyle(n).visibility),'hidden');
assert.ok(await page.locator('.us-cco__frame').first().evaluate(n=>n.getBoundingClientRect().height>=360),'loading frame reserves its viewport');
assert.ok(await page.locator('.us-cco__frame').first().evaluate(n=>n.getBoundingClientRect().height>=480),'480px minimum');
const loader=page.locator('.us-cco__panel[aria-busy="true"] > .us-cco__loader').first();
assert.equal(await loader.evaluate(n=>getComputedStyle(n).animationName),'section-circles-forward');
assert.equal(await loader.evaluate(n=>getComputedStyle(n,'::after').animationName),'section-circles-back');
assert.equal(await tabs.first().locator('.us-tab-loading-spinner').evaluate(n=>getComputedStyle(n).animationName),'us-tab-loading-spin');
await tabs.nth(1).click();await tabs.nth(1).locator('[data-us-cco-spinner]').waitFor();assert.equal(await tabs.first().locator('[data-us-cco-spinner]').count(),0);
await page.waitForFunction(()=>window.UnionSuiteCCO.diagnostics()[0].frames.every(f=>f.state==='ready'));assert.equal(await page.locator('[data-us-cco-spinner]').count(),0);
await tabs.first().click();await page.waitForFunction(()=>document.querySelector('[role=tab]').getAttribute('aria-busy')==='false');assert.equal(await page.locator('[data-us-cco-spinner]').count(),0);
await page.waitForFunction(()=>[...document.querySelectorAll('.us-cco__frame')].every(n=>n.style.visibility!== 'hidden'));
service.options.preload='sequential-idle';service.options.frameDelay[ids.pages[1]]=1800;
await page.reload();await page.waitForFunction(id=>window.UnionSuiteCCO?.diagnostics()[0]?.frames.some(f=>f.id===id&&f.state==='loading'),ids.pages[1]);
await page.waitForTimeout(200);assert.equal(await page.locator('[data-us-cco-spinner]').count(),0);
await tabs.nth(1).click();await tabs.nth(1).locator('[data-us-cco-spinner]').waitFor();
await tabs.first().click();assert.equal(await page.locator('[data-us-cco-spinner]').count(),0);
await page.waitForFunction(id=>window.UnionSuiteCCO.diagnostics()[0].frames.some(f=>f.id===id&&f.state==='ready'),ids.pages[1]);
await tabs.nth(1).click();await tabs.nth(1).locator('[data-us-cco-spinner]').waitFor();await page.waitForFunction(()=>document.querySelectorAll('[role=tab]')[1].getAttribute('aria-busy')==='false');
await page.emulateMedia({reducedMotion:'reduce'});await tabs.nth(2).click();
await page.evaluate(()=>window.UnionSuiteCCO.dispose());await page.waitForTimeout(200);assert.equal(await page.locator('[data-us-cco-spinner]').count(),0);
console.log('PASS delayed native spinner, hidden visual loading message, silent sequential preload, click mid-load, switching away, ready/warm cleanup and disposal.');
}finally{await browser.close();await new Promise(r=>service.server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
