/* Preview only: completion effects for review; no task persistence. */
const shapes={star:'<path d="m12 1 3 7 8 1-6 5 2 8-7-4-7 4 2-8-6-5 8-1z"/>',moon:'<path d="M17 2A10 10 0 1 0 22 17 10 10 0 0 1 17 2Z"/>',bat:'<path d="m10 8-1-4 3 2 3-2-1 4c3-4 6-5 10-4-3 4-3 7-2 10-3-2-5-2-7 1l-3 4-3-4c-2-3-4-3-7-1 1-3 1-6-2-10 4-1 7 0 10 4Z"/>',leaf:'<path d="M21 2C9 1 1 8 5 17S23 20 21 2Z"/><path d="m6 20 10-12" stroke="white" stroke-width="1"/>',confetti:'<rect x="7" y="3" width="8" height="17" rx="2"/>'};
const variants=[['confetti','01','Everyday confetti','A small burst of brand-coloured paper. The clearest everyday celebration.'],['night','02','Moons & stars','A crescent and scattered stars float upwards. Suggested when dark mode is active.'],['bats','03','Halloween bats','A few fluttering silhouettes, with warm sparkles. Suggested for 31 October.'],['ripple','04','Quiet ripple','One soft ring and a drawn tick. A restrained everyday alternative.'],['leaves','05','Little leaf burst','A gentle green flutter. An organic alternative to confetti.']];
const state=new Map();
const app=document.querySelector('#examples');
const tick='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4 10-10"/></svg>';
app.innerHTML=variants.map(([kind,num,title,description])=>`<section class="demo ${kind==='night'?'dark':''}" data-kind="${kind}"><div class="intro"><span class="num">${num} / ${kind==='night'?'Night':kind==='bats'?'Seasonal':'Everyday'}</span><h2>${title}</h2><p>${description}</p></div><div class="sample"><div class="panel-titlebar"><strong>My Tasks</strong><span class="count">2 outstanding</span><button type="button" class="us-task-completed-toggle" aria-label="Show completed tasks" title="Show completed tasks" aria-pressed="false">Show completed</button></div><div class="rows">${['Confirm membership details','Return a member’s call'].map((title,i)=>`<div class="task" data-title="${title}"><button class="check" type="button" role="checkbox" aria-checked="false" aria-label="Complete task: ${title}">${tick}</button><div class="copy"><strong>${title}</strong><span>${i?'Alex Morgan · Due tomorrow':'Sam Taylor · Due today'}</span></div><span class="due">${i?'Tomorrow':'Today'}</span></div>`).join('')}<div class="empty" hidden>All caught up.</div></div><div class="sample-footer"><span class="feedback" role="status" aria-live="polite">Click a checkbox to try it.</span><button class="reset" type="button">Reset</button></div></div></section>`).join('');
function reduced(){return document.querySelector('#motion').checked||matchMedia('(prefers-reduced-motion: reduce)').matches}
function clearRow(row){const s=state.get(row);if(s){s.timers.forEach(clearTimeout);s.animations.forEach(a=>a.cancel());s.particles.forEach(p=>p.remove());state.delete(row)}}
function update(card){const n=card.querySelectorAll('.check[aria-checked="false"]').length;card.querySelector('.count').textContent=n+' outstanding';card.querySelector('.empty').hidden=!!card.querySelector('.task:not([hidden])')||!document.querySelector('#exit').checked;}
function reset(card){card.querySelectorAll('.task').forEach(row=>{clearRow(row);row.hidden=false;row.classList.remove('done');row.removeAttribute('style');const c=row.querySelector('.check');c.setAttribute('aria-checked','false');c.setAttribute('aria-label','Complete task: '+row.dataset.title)});card.querySelector('.feedback').textContent='Click a checkbox to try it.';update(card)}
function burst(row,kind,s){if(reduced())return;const rect=row.querySelector('.check').getBoundingClientRect();const cx=rect.left+rect.width/2,cy=rect.top+rect.height/2;
const count=kind==='ripple'?1:kind==='bats'?7:kind==='night'?10:12;
for(let i=0;i<count;i++){const el=document.createElement('span');el.className='particle '+kind;el.setAttribute('aria-hidden','true');el.style.left=cx+'px';el.style.top=cy+'px';const glyph=kind==='night'?(i===0?'moon':'star'):kind==='bats'?(i<5?'bat':'star'):kind==='leaves'?'leaf':'confetti';el.innerHTML=kind==='ripple'?'':`<svg viewBox="0 0 24 24">${shapes[glyph]}</svg>`;const palette=kind==='night'?['#ffe5a0','#d7e8ff','#acbaff']:kind==='bats'?['#8f79c6','#6f569f','#e8aa58']:kind==='leaves'?['#47a77b','#92c86a','#287b65']:['#ed9554','#4aa9ba','#aa8ed6','#e5b653'];el.style.color=palette[i%palette.length];document.body.append(el);s.particles.push(el);const angle=(-165+i*145/Math.max(1,count-1))*Math.PI/180;const distance=48+(i%4)*16;const dx=Math.cos(angle)*distance,dy=Math.sin(angle)*distance;const duration=(kind==='night'||kind==='leaves'?1100:kind==='bats'?1050:800)*(document.querySelector('#slow').checked?2:1);
let frames=kind==='ripple'?[{transform:'translate(-50%,-50%) scale(.5)',opacity:.7},{transform:'translate(-50%,-50%) scale(3)',opacity:0}]:[{transform:'translate(-50%,-50%) scale(.3)',opacity:0},{offset:.2,transform:`translate(${dx*.4}px,${dy*.6}px) scale(1)`,opacity:1},{offset:.6,transform:`translate(${dx}px,${dy}px) rotate(${i%2?25:-25}deg) scale(1)`,opacity:.9},{transform:`translate(${dx*1.2}px,${dy+(kind==='night'?-28:kind==='bats'?-20:55)}px) rotate(${i%2?90:-65}deg) scale(.6)`,opacity:0}];const a=el.animate(frames,{duration,easing:'ease-out',fill:'forwards'});s.animations.push(a);if(glyph==='bat'){const flap=el.querySelector('svg').animate([{transform:'scaleX(1)'},{transform:'scaleX(.35)'},{transform:'scaleX(1)'}],{duration:160,iterations:Math.ceil(duration/160)});s.animations.push(flap)}a.finished.then(()=>el.remove()).catch(()=>{});}}
function complete(row){const card=row.closest('.demo');if(row.classList.contains('done')){clearRow(row);row.classList.remove('done');row.querySelector('.check').setAttribute('aria-checked','false');row.querySelector('.check').setAttribute('aria-label','Complete task: '+row.dataset.title);update(card);card.querySelector('.feedback').textContent='Task reopened.';return}clearRow(row);const s={animations:[],timers:[],particles:[]};state.set(row,s);row.classList.add('done');const btn=row.querySelector('.check');btn.setAttribute('aria-checked','true');btn.setAttribute('aria-label','Reopen task: '+row.dataset.title);update(card);card.querySelector('.feedback').textContent='Completed: '+row.dataset.title;burst(row,card.dataset.kind,s);
if(document.querySelector('#exit').checked&&!card.querySelector('.us-task-completed-toggle[aria-pressed="true"]')){const hide=()=>{if(btn===document.activeElement){const next=Array.from(card.querySelectorAll('.check')).find(c=>c!==btn&&c.getAttribute('aria-checked')==='false');(next||card.querySelector('.reset')).focus()}row.hidden=true;update(card)};if(reduced()){hide();return}const speed=document.querySelector('#slow').checked?2:1;
const celebration=({night:1100,leaves:1100,bats:1050})[card.dataset.kind]||800;
s.timers.push(setTimeout(async()=>{
  try{
    const slide=row.animate([{transform:'translateX(0)',opacity:1},{transform:'translateX(-105%)',opacity:0}],{duration:450*speed,fill:'forwards',easing:'cubic-bezier(.4,0,.2,1)'});
    s.animations.push(slide);await slide.finished;
    if(state.get(row)!==s)return;
    const height=row.getBoundingClientRect().height;
    const collapse=row.animate([{height:height+'px',minHeight:'0px',opacity:0},{height:'0px',minHeight:'0px',paddingTop:'0px',paddingBottom:'0px',borderTopWidth:'0px',opacity:0}],{duration:300*speed,fill:'forwards',easing:'ease-in-out'});
    s.animations.push(collapse);await collapse.finished;
    if(state.get(row)===s)hide();
  }catch(error){if(error.name!=='AbortError')console.warn('Preview exit could not finish',error)}
},(celebration+100)*speed));}}

app.addEventListener('click',e=>{const check=e.target.closest('.check');if(check)complete(check.closest('.task'));const button=e.target.closest('.reset');if(button)reset(button.closest('.demo'))});
app.addEventListener('keydown',e=>{if(e.key===' '&&e.target.matches('.check')){e.preventDefault();e.target.click()}});
document.querySelector('#all').onclick=()=>document.querySelectorAll('.demo').forEach(card=>{reset(card);complete(card.querySelector('.task'))});
document.querySelector('#reset').onclick=()=>document.querySelectorAll('.demo').forEach(reset);
for(const id of ['exit','motion','slow'])document.querySelector('#'+id).onchange=()=>{document.body.classList.toggle('reduce',reduced());document.querySelectorAll('.demo').forEach(reset)};
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{document.body.classList.toggle('reduce',reduced());document.querySelectorAll('.demo').forEach(reset)});
document.querySelector('#theme').onchange=e=>{document.body.dataset.theme=e.target.value;document.querySelectorAll('.demo').forEach(card=>card.classList.toggle('dark',e.target.value==='dark'||e.target.value==='mixed'&&card.dataset.kind==='night'))};

app.addEventListener('click',e=>{const toggle=e.target.closest('.us-task-completed-toggle');if(!toggle)return;const on=toggle.getAttribute('aria-pressed')!=='true';toggle.setAttribute('aria-pressed',String(on));toggle.textContent=on?'Showing completed':'Show completed';const card=toggle.closest('.demo');card.querySelectorAll('.task.done').forEach(row=>{clearRow(row);if(on){const hidden=row.hidden;row.hidden=false;if(hidden&&!reduced()){const a=row.animate([{height:'0px',minHeight:'0px',paddingTop:'0px',paddingBottom:'0px',opacity:0},{height:row.offsetHeight+'px',minHeight:'0px',opacity:1}],{duration:300,easing:'ease-in-out'});state.set(row,{animations:[a],timers:[],particles:[]});}}else if(document.querySelector('#exit').checked)row.hidden=true;});update(card);});
